language: android
sudo: false
jdk: oraclejdk7
android:
  components:
    - tools
      - build-tools-23.0.2
        - android-23
          - extra-android-m2repository
            - extra-android-support
            script:
            - ./gradlew assembleRelease
            deploy:
              provider: releases
                file: demo/demo-release-unsigned.apk
                  skip_cleanup: true
                    on:
                        tags: true
